/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.92
 * Generated at: 2018-12-10 10:32:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Shopping Cart Website</title>\r\n");
      out.write("<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header>\r\n");
      out.write("\t  <div class=\"row\">\r\n");
      out.write("\t   <div class=\"logo\">\r\n");
      out.write("\t\t<img src=\"logo1.jpg\">\r\n");
      out.write("\t   </div>\r\n");
      out.write("\t  \r\n");
      out.write("\t   <div class=\"hero\">\r\n");
      out.write("\t\t<h1>Electronix Pet</h1>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<ul class=\"main-nav\">\r\n");
      out.write("\t\t\t<li class=\"active\"><a href=\"home.html\">HOME</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"about.html\">ABOUT</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"login.jsp\">LOGIN</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"registration.jsp\">REGISTER</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"productImage.jsp\">CART</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t<!-- <div class=\"hhero\">\r\n");
      out.write("\t\t<h1>Electronix Pet</h1>\r\n");
      out.write("\t</div>  -->\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  \r\n");
      out.write("\t\r\n");
      out.write("\t<!-- \r\n");
      out.write("\t\t<div class=\"button\">\r\n");
      out.write("\t\t\t<a href=\"\" class=\"btn btn-one\"> Watch Video</a>\r\n");
      out.write("\t\t\t<a href=\"\" class=\"btn btn-two\"> Explore</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t -->\t\r\n");
      out.write("\t<!--  <div class=\"mobile\">\r\n");
      out.write("\t\t<a href=\"#\"><img src=\"mobile.jpg\" ></a>\r\n");
      out.write("\t\t<div class=\"centered\"><h2>Mobile Phones</h2></div>\r\n");
      out.write("\t   </div> -->\r\n");
      out.write("\r\n");
      out.write("<!-- <h2 class=\"w3-center\">Automatic Slideshow</h2> -->\r\n");
      out.write("</header>\r\n");
      out.write("<div class=\"slide\">\r\n");
      out.write("  <img class=\"mySlides\" src=\"cart.jpg\">\r\n");
      out.write("  <img class=\"mySlides\" src=\"cart.jpg\">\r\n");
      out.write("  <img class=\"mySlides\" src=\"bags.jpg\">\r\n");
      out.write("  <img class=\"mySlides\" src=\"girlwithbags.jpg\">\r\n");
      out.write("</div>\r\n");
      out.write("<!-- </header> -->\r\n");
      out.write("<script>\r\n");
      out.write("var myIndex = 0;\r\n");
      out.write("carousel();\r\n");
      out.write("\r\n");
      out.write("function carousel() {\r\n");
      out.write("    var i;\r\n");
      out.write("    var x = document.getElementsByClassName(\"mySlides\");\r\n");
      out.write("    for (i = 0; i < x.length; i++) {\r\n");
      out.write("       x[i].style.display = \"none\";  \r\n");
      out.write("    }\r\n");
      out.write("    myIndex++;\r\n");
      out.write("    if (myIndex > x.length) {myIndex = 1}    \r\n");
      out.write("    x[myIndex-1].style.display = \"block\";  \r\n");
      out.write("    setTimeout(carousel, 2000); // Change image every 2 seconds\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("<footer class=\"foot\">\r\n");
      out.write("\t\r\n");
      out.write("\t<p>&copy; 2018 ElectronixPet.com</p>\r\n");
      out.write("</footer>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
